# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GraphInfo
                                 A QGIS plugin
 Graph show info about an active layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-11-20
        git sha              : $Format:%H$
        copyright            : (C) 2025 by David Torres
        email                : davidt1987@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .graph_layer_dialog import GraphInfoDialog
import os.path


class GraphInfo:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GraphInfo_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Graph layer')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GraphInfo', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/graph_layer/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Statistical Graphs'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Graph layer'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""
        from qgis.core import QgsProject
        from qgis.PyQt.QtWidgets import QMessageBox

        # Get the active layer
        layer = self.iface.activeLayer()

        # Check if there is an active layer
        if not layer:
            QMessageBox.warning(
                self.iface.mainWindow(),
                "No Active Layer",
                "Please select an active layer before running this plugin."
            )
            return

        # Check if the layer has features
        if layer.featureCount() == 0:
            QMessageBox.warning(
                self.iface.mainWindow(),
                "Empty Layer",
                "The active layer has no features."
            )
            return

        # Get layer name
        layer_name = layer.name()

        # Get field names
        field_names = [field.name() for field in layer.fields()]

        # Analyze all columns to find those with repeated values suitable for bar charts
        column_value_counts = {}
        features_data = []

        # First pass: collect all data and count unique values per column
        for feature in layer.getFeatures():
            feature_data = {}

            for field_name in field_names:
                # Get field value
                field_value = feature[field_name]

                # Convert to string
                if field_value is not None:
                    field_value = str(field_value)
                else:
                    field_value = 'N/A'

                # Handle NULL/empty values
                if field_value == '' or field_value == 'NULL':
                    field_value = 'N/A'

                # Store in feature data
                feature_data[field_name] = field_value

                # Count unique values for this column
                if field_name not in column_value_counts:
                    column_value_counts[field_name] = {}

                if field_value in column_value_counts[field_name]:
                    column_value_counts[field_name][field_value] += 1
                else:
                    column_value_counts[field_name][field_value] = 1

            features_data.append(feature_data)

        # Identify columns suitable for bar charts
        # A column is suitable if it has repeated values (unique count < total count)
        # and not too many unique values (< 50% of total records or max 100 unique values)
        total_features = len(features_data)
        graphable_columns = []

        for field_name, value_counts in column_value_counts.items():
            unique_count = len(value_counts)

            # Column must have repeated values (not all unique)
            # and reasonable number of categories for visualization
            if unique_count < total_features and unique_count <= min(100, total_features * 0.5):
                graphable_columns.append(field_name)

        # Check if we have graphable columns
        if not graphable_columns:
            QMessageBox.warning(
                self.iface.mainWindow(),
                "No Graphable Columns",
                "No columns found with repeated values suitable for bar chart visualization.\n\n"
                "All columns appear to have unique values for each feature."
            )
            return

        # Filter features_data to only include graphable columns
        filtered_features_data = []
        for feature in features_data:
            filtered_feature = {col: feature[col] for col in graphable_columns}
            filtered_features_data.append(filtered_feature)

        # Select the first graphable column as default for initial graph
        default_column = graphable_columns[0]
        default_counts = column_value_counts[default_column]

        # Sort by count (descending)
        default_counts = dict(sorted(default_counts.items(), key=lambda x: x[1], reverse=True))

        # Get only top 10 categories for the graph
        top_10_counts = dict(list(default_counts.items())[:10])

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = GraphInfoDialog()

        # Plot the data with graphable columns only
        self.dlg.plot_column_data_dynamic(default_column, top_10_counts,
                                         filtered_features_data, graphable_columns, layer_name)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
