# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GraphInfoDialog
                                 A QGIS plugin
 Graph show info about an active layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-20
        git sha              : $Format:%H$
        copyright            : (C) 2025 by David Torres
        email                : davidt1987@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QVBoxLayout, QTableWidgetItem
from qgis.PyQt.QtCore import Qt

import matplotlib
matplotlib.use('Qt5Agg')
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'graph_layer_dialog_base.ui'))


class GraphInfoDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(GraphInfoDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # Create matplotlib figure and canvas
        self.figure = Figure(figsize=(8, 5))
        self.canvas = FigureCanvas(self.figure)

        # Add canvas to the graph_widget
        layout = QVBoxLayout(self.graph_widget)
        layout.addWidget(self.canvas)

        # Store all features data for dynamic column selection
        self.all_features_data = []

        # Store graphable columns list
        self.graphable_columns = []

        # Connect table header click signal
        self.data_table.horizontalHeader().sectionClicked.connect(self.on_table_header_clicked)

    def plot_column_data_dynamic(self, column_name, column_counts, features_data, graphable_columns, layer_name=None):
        """
        Plot a bar chart with column data and populate the data table with only graphable columns

        :param column_name: Name of the column to plot initially
        :param column_counts: Dictionary with column values as keys and counts as values
        :param features_data: List of dictionaries with feature data for the table (only graphable columns)
        :param graphable_columns: List of column names that are suitable for graphing
        :param layer_name: Name of the layer to display in the title (optional)
        """
        # Store all features data for later use when clicking on columns
        self.all_features_data = features_data

        # Store graphable columns
        self.graphable_columns = graphable_columns

        # Update title with layer name if provided
        if layer_name:
            self.label_title.setText(f"Field Statistics - {layer_name}")

        # Plot the graph with the selected column data
        self.plot_column_data(column_name, column_counts)

        # Populate the data table with features data (only graphable columns)
        self.populate_table_dynamic(features_data, graphable_columns)

    def plot_schooltype_data(self, schooltype_counts, features_data):
        """
        Plot a bar chart with SchoolType data and populate the data table
        (Deprecated - kept for backwards compatibility)

        :param schooltype_counts: Dictionary with SchoolType values as keys and counts as values
        :param features_data: List of dictionaries with feature data for the table
        """
        # Store all features data for later use when clicking on columns
        self.all_features_data = features_data

        # Plot the graph with SchoolType data
        self.plot_column_data('SchoolType', schooltype_counts)

        # Populate the data table with features data
        self.populate_table(features_data)

    def plot_column_data(self, column_name, column_counts):
        """
        Plot a bar chart with column data

        :param column_name: Name of the column being plotted
        :param column_counts: Dictionary with column values as keys and counts as values
        """
        # Clear previous plot
        self.figure.clear()

        # Create subplot
        ax = self.figure.add_subplot(111)

        # Prepare data - ensure all values are Python native types
        categories = [str(key) for key in column_counts.keys()]
        counts = [int(value) for value in column_counts.values()]

        # Create bar chart
        bars = ax.bar(categories, counts, color='steelblue', edgecolor='black', alpha=0.7)

        # Add value labels on top of bars
        for bar in bars:
            height = bar.get_height()
            ax.text(bar.get_x() + bar.get_width()/2., height,
                   f'{int(height)}',
                   ha='center', va='bottom', fontsize=9)

        # Customize plot with labels and title
        ax.set_xlabel(column_name, fontsize=12, fontweight='bold')
        ax.set_ylabel('Count', fontsize=12, fontweight='bold')
        ax.set_title(f'Distribution of {column_name} in Active Layer', fontsize=14, fontweight='bold')
        ax.grid(axis='y', alpha=0.3, linestyle='--')

        # Rotate x-axis labels if there are many categories
        if len(categories) > 5:
            ax.tick_params(axis='x', rotation=45)
            self.figure.tight_layout()

        # Refresh canvas
        self.canvas.draw()

    def on_table_header_clicked(self, column_index):
        """
        Handle table header click - update graph to show distribution of clicked column

        :param column_index: Index of the clicked column
        """
        # Use graphable_columns if available, otherwise extract from first feature
        if self.graphable_columns:
            columns = self.graphable_columns
        elif self.all_features_data:
            columns = list(self.all_features_data[0].keys())
        else:
            return

        # Get the column name
        if column_index < len(columns) and self.all_features_data:
            clicked_column = columns[column_index]

            # Count values for the selected column
            column_counts = {}
            for feature in self.all_features_data:
                value = feature.get(clicked_column, 'N/A')

                # Handle NULL/empty values
                if value is None or value == '' or value == 'NULL':
                    value = 'N/A'

                # Count occurrences
                if value in column_counts:
                    column_counts[value] += 1
                else:
                    column_counts[value] = 1

            # Sort by count (descending)
            column_counts = dict(sorted(column_counts.items(), key=lambda x: x[1], reverse=True))

            # Get only top 10 categories
            top_10_counts = dict(list(column_counts.items())[:10])

            # Plot the graph with the selected column data
            self.plot_column_data(clicked_column, top_10_counts)

    def populate_table_dynamic(self, features_data, columns):
        """
        Populate the QTableWidget with feature data using dynamic columns

        :param features_data: List of dictionaries with feature data
        :param columns: List of column names to display
        """
        # Set the number of rows and columns
        self.data_table.setRowCount(len(features_data))
        self.data_table.setColumnCount(len(columns))

        # Set column headers
        self.data_table.setHorizontalHeaderLabels(columns)

        # Populate the table
        for row, feature in enumerate(features_data):
            for col, field_name in enumerate(columns):
                # Get the value from the feature
                value = feature.get(field_name, 'N/A')

                # Create table item
                item = QTableWidgetItem(str(value))
                item.setFlags(item.flags() & ~Qt.ItemIsEditable)  # Make read-only

                self.data_table.setItem(row, col, item)

        # Resize columns to fit content
        self.data_table.resizeColumnsToContents()

        # Make header clickable and add cursor
        header = self.data_table.horizontalHeader()
        header.setCursor(Qt.PointingHandCursor)

        # Add tooltip to headers to indicate clickability
        for col, field_name in enumerate(columns):
            header_item = self.data_table.horizontalHeaderItem(col)
            if header_item is None:
                header_item = QTableWidgetItem()
                self.data_table.setHorizontalHeaderItem(col, header_item)
            header_item.setToolTip(f"Click to show {field_name} distribution in graph")

    def populate_table(self, features_data):
        """
        Populate the QTableWidget with feature data
        (Deprecated - uses dynamic columns instead of hardcoded list)

        :param features_data: List of dictionaries with feature data
        """
        # Extract columns dynamically from the first feature if available
        if not features_data:
            return

        columns = list(features_data[0].keys())

        # Use the dynamic table population method
        self.populate_table_dynamic(features_data, columns)
