# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GraphInfoDialog
                                 A QGIS plugin
 Graph show info about an active layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-20
        git sha              : $Format:%H$
        copyright            : (C) 2025 by David Torres
        email                : davidt1987@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QVBoxLayout

import matplotlib
matplotlib.use('Qt5Agg')
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'graph_layer_dialog_base.ui'))


class GraphInfoDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(GraphInfoDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # Create matplotlib figure and canvas
        self.figure = Figure(figsize=(8, 5))
        self.canvas = FigureCanvas(self.figure)

        # Add canvas to the graph_widget
        layout = QVBoxLayout(self.graph_widget)
        layout.addWidget(self.canvas)

    def plot_schooltype_data(self, schooltype_counts):
        """
        Plot a bar chart with SchoolType data

        :param schooltype_counts: Dictionary with SchoolType values as keys and counts as values
        """
        # Clear previous plot
        self.figure.clear()

        # Create subplot
        ax = self.figure.add_subplot(111)

        # Prepare data - ensure all values are Python native types
        schooltypes = [str(key) for key in schooltype_counts.keys()]
        counts = [int(value) for value in schooltype_counts.values()]

        # Create bar chart
        bars = ax.bar(schooltypes, counts, color='steelblue', edgecolor='black', alpha=0.7)

        # Add value labels on top of bars
        for bar in bars:
            height = bar.get_height()
            ax.text(bar.get_x() + bar.get_width()/2., height,
                   f'{int(height)}',
                   ha='center', va='bottom', fontsize=9)

        # Customize plot
        ax.set_xlabel('School Type', fontsize=12, fontweight='bold')
        ax.set_ylabel('Count', fontsize=12, fontweight='bold')
        ax.set_title('Distribution of School Types in Active Layer', fontsize=14, fontweight='bold')
        ax.grid(axis='y', alpha=0.3, linestyle='--')

        # Rotate x-axis labels if there are many categories
        if len(schooltypes) > 5:
            ax.tick_params(axis='x', rotation=45)
            self.figure.tight_layout()

        # Refresh canvas
        self.canvas.draw()
