# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GraphInfo
                                 A QGIS plugin
 Graph show info about an active layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-11-20
        git sha              : $Format:%H$
        copyright            : (C) 2025 by David Torres
        email                : davidt1987@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .graph_layer_dialog import GraphInfoDialog
import os.path


class GraphInfo:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GraphInfo_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Graph layer')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GraphInfo', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/graph_layer/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Statistical Graphs'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Graph layer'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""
        from qgis.core import QgsProject
        from qgis.PyQt.QtWidgets import QMessageBox

        # Get the active layer
        layer = self.iface.activeLayer()

        # Check if there is an active layer
        if not layer:
            QMessageBox.warning(
                self.iface.mainWindow(),
                "No Active Layer",
                "Please select an active layer before running this plugin."
            )
            return

        # Check if the layer has features
        if layer.featureCount() == 0:
            QMessageBox.warning(
                self.iface.mainWindow(),
                "Empty Layer",
                "The active layer has no features."
            )
            return

        # Get field names
        field_names = [field.name() for field in layer.fields()]

        # Required fields
        required_fields = ['CDCode', 'Region', 'CountyName', 'DistrictName', 'SchoolName',
                          'SchoolType', 'Status', 'SchoolLevel', 'City']

        # Check if all required fields exist
        missing_fields = [f for f in required_fields if f not in field_names]
        if missing_fields:
            QMessageBox.warning(
                self.iface.mainWindow(),
                "Missing Fields",
                f"The active layer is missing the following fields: {', '.join(missing_fields)}\n\nAvailable fields: {', '.join(field_names)}"
            )
            return

        # Count SchoolType values and collect feature data
        schooltype_counts = {}
        features_data = []

        for feature in layer.getFeatures():
            # Get SchoolType value and convert QVariant to Python type
            schooltype_value = feature['SchoolType']

            # Convert QVariant to Python native type (str)
            if schooltype_value is not None:
                schooltype_value = str(schooltype_value)

            # Handle NULL values
            if schooltype_value is None or schooltype_value == '' or schooltype_value == 'NULL':
                schooltype_value = 'N/A'

            # Count occurrences
            if schooltype_value in schooltype_counts:
                schooltype_counts[schooltype_value] += 1
            else:
                schooltype_counts[schooltype_value] = 1

            # Store feature data
            feature_data = {
                'CDCode': str(feature['CDCode']) if feature['CDCode'] is not None else 'N/A',
                'Region': str(feature['Region']) if feature['Region'] is not None else 'N/A',
                'CountyName': str(feature['CountyName']) if feature['CountyName'] is not None else 'N/A',
                'DistrictName': str(feature['DistrictName']) if feature['DistrictName'] is not None else 'N/A',
                'SchoolName': str(feature['SchoolName']) if feature['SchoolName'] is not None else 'N/A',
                'SchoolType': schooltype_value,
                'Status': str(feature['Status']) if feature['Status'] is not None else 'N/A',
                'SchoolLevel': str(feature['SchoolLevel']) if feature['SchoolLevel'] is not None else 'N/A',
                'City': str(feature['City']) if feature['City'] is not None else 'N/A'
            }
            features_data.append(feature_data)

        # Check if we have data to plot
        if not schooltype_counts:
            QMessageBox.warning(
                self.iface.mainWindow(),
                "No Data",
                "No data found in the 'SchoolType' field."
            )
            return

        # Sort by count (descending)
        schooltype_counts = dict(sorted(schooltype_counts.items(), key=lambda x: x[1], reverse=True))

        # Get only top 10 categories for the graph
        top_10_schooltypes = dict(list(schooltype_counts.items())[:10])

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = GraphInfoDialog()

        # Plot the data (top 10 for graph) and pass ALL features data for the table
        self.dlg.plot_schooltype_data(top_10_schooltypes, features_data)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
