# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GraphInfoDialog
                                 A QGIS plugin
 Graph show info about an active layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-20
        git sha              : $Format:%H$
        copyright            : (C) 2025 by David Torres
        email                : davidt1987@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QVBoxLayout, QTableWidgetItem
from qgis.PyQt.QtCore import Qt

import matplotlib
matplotlib.use('Qt5Agg')
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'graph_layer_dialog_base.ui'))


class GraphInfoDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(GraphInfoDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # Create matplotlib figure and canvas for bar chart
        self.figure = Figure(figsize=(8, 5))
        self.canvas = FigureCanvas(self.figure)

        # Add canvas to the graph_widget
        layout = QVBoxLayout(self.graph_widget)
        layout.addWidget(self.canvas)

        # Create matplotlib figure and canvas for line chart
        self.line_figure = Figure(figsize=(8, 4))
        self.line_canvas = FigureCanvas(self.line_figure)

        # Add canvas to the line_graph_widget
        line_layout = QVBoxLayout(self.line_graph_widget)
        line_layout.addWidget(self.line_canvas)

        # Store all features data for dynamic column selection
        self.all_features_data = []

        # Store graphable columns list
        self.graphable_columns = []

        # Store current column being graphed
        self.current_column = None

        # Store filtered data for line chart
        self.filtered_data = []
        self.selected_filter_value = None

        # Connect table header click signal
        self.data_table.horizontalHeader().sectionClicked.connect(self.on_table_header_clicked)

        # Connect value filter dropdown
        self.value_filter.currentIndexChanged.connect(self.on_filter_changed)

        # Connect column selector dropdown
        self.column_selector.currentIndexChanged.connect(self.on_column_selected)

        # Connect clear button
        self.clear_button.clicked.connect(self.clear_filters)

    def plot_column_data_dynamic(self, column_name, column_counts, features_data, graphable_columns, layer_name=None):
        """
        Plot a bar chart with column data and populate the data table with only graphable columns

        :param column_name: Name of the column to plot initially
        :param column_counts: Dictionary with column values as keys and counts as values
        :param features_data: List of dictionaries with feature data for the table (only graphable columns)
        :param graphable_columns: List of column names that are suitable for graphing
        :param layer_name: Name of the layer to display in the title (optional)
        """
        # Store all features data for later use when clicking on columns
        self.all_features_data = features_data

        # Store graphable columns
        self.graphable_columns = graphable_columns

        # Update title with layer name if provided
        if layer_name:
            self.label_title.setText(f"Field Statistics - {layer_name}")

        # Plot the graph with the selected column data
        self.plot_column_data(column_name, column_counts)

        # Populate the data table with features data (only graphable columns)
        self.populate_table_dynamic(features_data, graphable_columns)

    def plot_schooltype_data(self, schooltype_counts, features_data):
        """
        Plot a bar chart with SchoolType data and populate the data table
        (Deprecated - kept for backwards compatibility)

        :param schooltype_counts: Dictionary with SchoolType values as keys and counts as values
        :param features_data: List of dictionaries with feature data for the table
        """
        # Store all features data for later use when clicking on columns
        self.all_features_data = features_data

        # Plot the graph with SchoolType data
        self.plot_column_data('SchoolType', schooltype_counts)

        # Populate the data table with features data
        self.populate_table(features_data)

    def plot_column_data(self, column_name, column_counts):
        """
        Plot a bar chart with column data

        :param column_name: Name of the column being plotted
        :param column_counts: Dictionary with column values as keys and counts as values
        """
        # Store current column
        self.current_column = column_name

        # Update value filter dropdown with distinct values
        self.update_value_filter(column_counts)

        # Clear previous plot
        self.figure.clear()

        # Create subplot
        ax = self.figure.add_subplot(111)

        # Prepare data - ensure all values are Python native types
        categories = [str(key) for key in column_counts.keys()]
        counts = [int(value) for value in column_counts.values()]

        # Create bar chart
        bars = ax.bar(categories, counts, color='steelblue', edgecolor='black', alpha=0.7)

        # Add value labels on top of bars
        for bar in bars:
            height = bar.get_height()
            ax.text(bar.get_x() + bar.get_width()/2., height,
                   f'{int(height)}',
                   ha='center', va='bottom', fontsize=9)

        # Customize plot with labels and title
        ax.set_xlabel(column_name, fontsize=12, fontweight='bold')
        ax.set_ylabel('Count', fontsize=12, fontweight='bold')
        ax.set_title(f'Distribution of {column_name} in Active Layer', fontsize=14, fontweight='bold')
        ax.grid(axis='y', alpha=0.3, linestyle='--')

        # Rotate x-axis labels if there are many categories
        if len(categories) > 5:
            ax.tick_params(axis='x', rotation=45)
            self.figure.tight_layout()

        # Refresh canvas
        self.canvas.draw()

    def on_table_header_clicked(self, column_index):
        """
        Handle table header click - update graph to show distribution of clicked column

        :param column_index: Index of the clicked column
        """
        # Use graphable_columns if available, otherwise extract from first feature
        if self.graphable_columns:
            columns = self.graphable_columns
        elif self.all_features_data:
            columns = list(self.all_features_data[0].keys())
        else:
            return

        # Get the column name
        if column_index < len(columns) and self.all_features_data:
            clicked_column = columns[column_index]

            # Count values for the selected column
            column_counts = {}
            for feature in self.all_features_data:
                value = feature.get(clicked_column, 'N/A')

                # Handle NULL/empty values
                if value is None or value == '' or value == 'NULL':
                    value = 'N/A'

                # Count occurrences
                if value in column_counts:
                    column_counts[value] += 1
                else:
                    column_counts[value] = 1

            # Sort by count (descending)
            column_counts = dict(sorted(column_counts.items(), key=lambda x: x[1], reverse=True))

            # Get only top 10 categories
            top_10_counts = dict(list(column_counts.items())[:10])

            # Plot the graph with the selected column data
            self.plot_column_data(clicked_column, top_10_counts)

    def populate_table_dynamic(self, features_data, columns):
        """
        Populate the QTableWidget with feature data using dynamic columns

        :param features_data: List of dictionaries with feature data
        :param columns: List of column names to display
        """
        # Set the number of rows and columns
        self.data_table.setRowCount(len(features_data))
        self.data_table.setColumnCount(len(columns))

        # Set column headers
        self.data_table.setHorizontalHeaderLabels(columns)

        # Populate the table
        for row, feature in enumerate(features_data):
            for col, field_name in enumerate(columns):
                # Get the value from the feature
                value = feature.get(field_name, 'N/A')

                # Create table item
                item = QTableWidgetItem(str(value))
                item.setFlags(item.flags() & ~Qt.ItemIsEditable)  # Make read-only

                self.data_table.setItem(row, col, item)

        # Resize columns to fit content
        self.data_table.resizeColumnsToContents()

        # Make header clickable and add cursor
        header = self.data_table.horizontalHeader()
        header.setCursor(Qt.PointingHandCursor)

        # Add tooltip to headers to indicate clickability
        for col, field_name in enumerate(columns):
            header_item = self.data_table.horizontalHeaderItem(col)
            if header_item is None:
                header_item = QTableWidgetItem()
                self.data_table.setHorizontalHeaderItem(col, header_item)
            header_item.setToolTip(f"Click to show {field_name} distribution in graph")

    def populate_table(self, features_data):
        """
        Populate the QTableWidget with feature data
        (Deprecated - uses dynamic columns instead of hardcoded list)

        :param features_data: List of dictionaries with feature data
        """
        # Extract columns dynamically from the first feature if available
        if not features_data:
            return

        columns = list(features_data[0].keys())

        # Use the dynamic table population method
        self.populate_table_dynamic(features_data, columns)

    def update_value_filter(self, column_counts):
        """
        Update the value filter dropdown with distinct values from the current column

        :param column_counts: Dictionary with column values as keys and counts as values
        """
        # Block signals to prevent triggering filter change while updating
        self.value_filter.blockSignals(True)

        # Clear existing items
        self.value_filter.clear()

        # Add "All" option as first item
        self.value_filter.addItem("All")

        # Add distinct values sorted by count (descending)
        sorted_values = sorted(column_counts.items(), key=lambda x: x[1], reverse=True)
        for value, count in sorted_values:
            self.value_filter.addItem(f"{value} ({count})", value)

        # Unblock signals
        self.value_filter.blockSignals(False)

    def plot_line_chart_single_column(self, filtered_data, filter_value, column_name):
        """
        Plot a line chart showing the distribution of a single selected column for the filtered data

        :param filtered_data: List of filtered feature data
        :param filter_value: The value that was used to filter
        :param column_name: The column to analyze and plot
        """
        # Clear previous plot
        self.line_figure.clear()

        if not filtered_data:
            self.line_graph_widget.setVisible(False)
            return

        # Hide bar chart and show line chart
        self.graph_widget.setVisible(False)
        self.line_graph_widget.setVisible(True)

        # Create subplot
        ax = self.line_figure.add_subplot(111)

        # Count occurrences for the selected column
        value_counts = {}
        for feature in filtered_data:
            value = feature.get(column_name, 'N/A')
            if value in value_counts:
                value_counts[value] += 1
            else:
                value_counts[value] = 1

        # Sort by count (descending) and get top 20 values
        sorted_counts = sorted(value_counts.items(), key=lambda x: x[1], reverse=True)[:20]

        # Prepare data for line chart
        categories = [str(val) for val, _ in sorted_counts]
        counts = [cnt for _, cnt in sorted_counts]

        # Create line chart
        x_positions = range(len(categories))
        ax.plot(x_positions, counts, marker='o', color='#1f77b4',
                linewidth=2.5, markersize=8, markerfacecolor='#ff7f0e',
                markeredgewidth=2, markeredgecolor='#1f77b4')

        # Add value labels on points
        for x, y in zip(x_positions, counts):
            ax.text(x, y, str(y), ha='center', va='bottom', fontsize=9, fontweight='bold')

        # Customize plot
        ax.set_xlabel(column_name, fontsize=11, fontweight='bold')
        ax.set_ylabel('Count', fontsize=11, fontweight='bold')
        ax.set_title(f'{column_name} Distribution - Filtered by {self.current_column} = {filter_value}',
                    fontsize=12, fontweight='bold')
        ax.set_xticks(x_positions)
        ax.set_xticklabels(categories, rotation=45, ha='right')
        ax.grid(axis='y', alpha=0.3, linestyle='--')
        ax.grid(axis='x', alpha=0.2, linestyle=':')

        self.line_figure.tight_layout()
        self.line_canvas.draw()

    def plot_line_chart(self, filtered_data, selected_value):
        """
        Plot a line chart showing the distribution of other columns for the filtered data
        (Deprecated - replaced by plot_line_chart_single_column)

        :param filtered_data: List of filtered feature data
        :param selected_value: The value that was used to filter
        """
        # Clear previous plot
        self.line_figure.clear()

        if not filtered_data or not self.graphable_columns:
            self.line_graph_widget.setVisible(False)
            return

        # Show the line graph widget
        self.line_graph_widget.setVisible(True)

        # Create subplot
        ax = self.line_figure.add_subplot(111)

        # Get columns excluding the current filter column
        other_columns = [col for col in self.graphable_columns if col != self.current_column]

        if not other_columns:
            self.line_graph_widget.setVisible(False)
            return

        # Count occurrences for each column
        column_data = {}
        for col in other_columns:
            counts = {}
            for feature in filtered_data:
                value = feature.get(col, 'N/A')
                if value in counts:
                    counts[value] += 1
                else:
                    counts[value] = 1
            # Get top 5 values for this column
            sorted_counts = sorted(counts.items(), key=lambda x: x[1], reverse=True)[:5]
            column_data[col] = sorted_counts

        # Prepare data for line chart
        x_positions = range(len(other_columns))

        # Plot lines for top values across columns
        colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd']

        # Get all unique values across columns (top 5)
        all_values = set()
        for col_values in column_data.values():
            for val, _ in col_values:
                all_values.add(val)

        # Plot line for each unique value
        for idx, value in enumerate(list(all_values)[:5]):
            y_values = []
            for col in other_columns:
                count = 0
                for val, cnt in column_data[col]:
                    if val == value:
                        count = cnt
                        break
                y_values.append(count)

            ax.plot(x_positions, y_values, marker='o', label=str(value),
                   color=colors[idx % len(colors)], linewidth=2, markersize=6)

        # Customize plot
        ax.set_xlabel('Columns', fontsize=11, fontweight='bold')
        ax.set_ylabel('Count', fontsize=11, fontweight='bold')
        ax.set_title(f'Distribution Analysis - Filtered by {self.current_column} = {selected_value}',
                    fontsize=12, fontweight='bold')
        ax.set_xticks(x_positions)
        ax.set_xticklabels(other_columns, rotation=45, ha='right')
        ax.grid(axis='y', alpha=0.3, linestyle='--')
        ax.legend(loc='best', fontsize=9)

        self.line_figure.tight_layout()
        self.line_canvas.draw()

    def on_filter_changed(self, index):
        """
        Handle filter dropdown change - filter table by selected value and show column selector

        :param index: Index of the selected item in the dropdown
        """
        if not self.current_column or not self.all_features_data:
            return

        # Get selected value
        selected_value = self.value_filter.currentData()

        # If "All" is selected or no data, show all records and hide column selector and line chart
        if index == 0 or selected_value is None:
            filtered_data = self.all_features_data
            self.graph_widget.setVisible(True)
            self.line_graph_widget.setVisible(False)
            self.label_column_select.setVisible(False)
            self.column_selector.setVisible(False)
            self.clear_button.setVisible(False)
            self.filtered_data = []
            self.selected_filter_value = None
        else:
            # Filter data by selected value
            filtered_data = [
                feature for feature in self.all_features_data
                if feature.get(self.current_column) == selected_value
            ]

            # Store filtered data for line chart
            self.filtered_data = filtered_data
            self.selected_filter_value = selected_value

            # Always show bar chart and hide line chart when filter changes
            self.graph_widget.setVisible(True)
            self.line_graph_widget.setVisible(False)

            # Populate column selector and show controls
            self.populate_column_selector()
            self.label_column_select.setVisible(True)
            self.column_selector.setVisible(True)
            self.clear_button.setVisible(True)

        # Update table with filtered data
        columns = self.graphable_columns if self.graphable_columns else list(self.all_features_data[0].keys())
        self.populate_table_dynamic(filtered_data, columns)

    def populate_column_selector(self):
        """
        Populate the column selector dropdown with available graphable columns (excluding current filter column)
        """
        # Block signals to prevent triggering column selection while updating
        self.column_selector.blockSignals(True)

        # Clear existing items
        self.column_selector.clear()

        # Add a placeholder option
        self.column_selector.addItem("-- Select a column --")

        # Get columns excluding the current filter column
        other_columns = [col for col in self.graphable_columns if col != self.current_column]

        # Add columns to selector
        for col in other_columns:
            self.column_selector.addItem(col)

        # Unblock signals
        self.column_selector.blockSignals(False)

        # Set to placeholder (index 0)
        self.column_selector.setCurrentIndex(0)

    def on_column_selected(self, index):
        """
        Handle column selector change - update line chart with selected column

        :param index: Index of the selected column in the dropdown
        """
        if not self.filtered_data or index < 0:
            return

        # Get selected column name
        selected_column = self.column_selector.currentText()

        # If placeholder is selected (index 0) or no valid column, hide line chart and show bar chart
        if index == 0 or not selected_column or selected_column == "-- Select a column --":
            self.graph_widget.setVisible(True)
            self.line_graph_widget.setVisible(False)
            return

        # Show line chart with filtered data for the selected column
        self.plot_line_chart_single_column(self.filtered_data, self.selected_filter_value, selected_column)

    def clear_filters(self):
        """
        Clear all filters and reset the view to show all data
        """
        # Reset value filter to "All" (index 0)
        self.value_filter.blockSignals(True)
        self.value_filter.setCurrentIndex(0)
        self.value_filter.blockSignals(False)

        # Hide column selector and clear button
        self.label_column_select.setVisible(False)
        self.column_selector.setVisible(False)
        self.clear_button.setVisible(False)

        # Show bar chart and hide line chart
        self.graph_widget.setVisible(True)
        self.line_graph_widget.setVisible(False)

        # Clear stored filter data
        self.filtered_data = []
        self.selected_filter_value = None

        # Show all data in table
        if self.all_features_data:
            columns = self.graphable_columns if self.graphable_columns else list(self.all_features_data[0].keys())
            self.populate_table_dynamic(self.all_features_data, columns)
